name: Android CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew test

    - name: Static Code Analysis
      run: ./gradlew lint

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: BuildArtifact
        path: app/build/outputs/

    - name: Deploy to Play Store
      run: echo "Deploying to Play Store - Placeholder"

